### ISSUE TITLE
bad conversion of identityref

### ISSUE THREAD

**Issue by ltn22** [alex-fddz/pycoreconf#1]
Hi Alex,

For a tutorial, I tried to use pycoreconf to transform data following this model

`module pokemon {

  yang-version 1.1;

  namespace "https://www.plido.net/pokemons";
  prefix pokemons;

  identity move-base-type {
    description "Identify pokemon attacks ";
  }

  identity move-absorb {
    base move-base-type;
  }

  identity move-amnesia {
    base move-base-type;
  }

  typedef move-type {
    type identityref {
      base move-base-type;
    }
  }

  container card {
    leaf name {
        type string {
            length "1..10";
        }
        mandatory true;
        description "name appearing on top of the card";
    }

    leaf hit-point {
        type uint32;
        mandatory true;
        description "hit points on top of the card";
    }

    list moves {
        key move;
        leaf move {
            type move-type;
        }
        leaf power {
            must "derived-from-or-self(../move, 'move-amnesia')"{
                error-message "Power is for Amnesia move only.";
            } 
            type uint8;
        }
        leaf accuracy {
            type uint8;
        }
        leaf power-point {
            type uint8;
        }
    }
  }
}`

the JSON file is

`{
  "pokemon:card": {
    "name": "Pikachu",
    "hit-point": 60,
    "moves": [
      {
        "move": "pokemon:move-absorb",
        "accuracy": 10,
        "power-point": 100
      },
      {
        "move": "pokemon:move-amnesia",
        "power": 110,
        "accuracy": 10,
        "power-point": 100
      }
    ]
  }
}
`

the result in CBOR shows that the move is not converted to the SID corresponding to the identity, but the string remains:

`A1                                      # map(1)
   19 03EC                              # unsigned(1004)
   A3                                   # map(3)
      07                                # unsigned(7)
      67                                # text(7)
         50696B61636875                 # "Pikachu"
      01                                # unsigned(1)
      18 3C                             # unsigned(60)
      02                                # unsigned(2)
      82                                # array(2)
         A3                             # map(3)
            02                          # unsigned(2)
            73                          # text(19)
               706F6B656D6F6E3A6D6F76652D6162736F7262 # "pokemon:move-absorb"
            01                          # unsigned(1)
            0A                          # unsigned(10)
            04                          # unsigned(4)
            18 64                       # unsigned(100)
         A4                             # map(4)
            02                          # unsigned(2)
            74                          # text(20)
               706F6B656D6F6E3A6D6F76652D616D6E65736961 # "pokemon:move-amnesia"
            03                          # unsigned(3)
            18 6E                       # unsigned(110)
            01                          # unsigned(1)
            0A                          # unsigned(10)
            04                          # unsigned(4)
            18 64                       # unsigned(100)
`

In the sid file we have this for the "move" :

`{
      "namespace": "data",
      "identifier": "/pokemon:card/moves/move",
      "sid": 1008,
      "type": "move-type"
    },
    `

I think we never had this problem with SCHC since we are doing in from CORECONF to JSON and you never used identityref in SDN.

I think the best way to solve this is to follow the links in pyang and change the "type":"nove-type" to "type":"identityref" and in pycoreconf put the sid in that case.

**Comment by ltn22** [comment]
I added a patch on ltn22's pyang, now the type is indentityref 

`    {
      "namespace": "data",
      "identifier": "/pokemon:card/moves/move",
      "sid": 1000008,
      "type": "identityref"
    },`

now pycoreconf should take it into account.

**Comment by alex-fddz** [comment]
I've created the branch idref to fix this issue. Can you try it out by cloning the repo and installing from source with `sudo python3 setup.py install" ? (you may need to first remove old version with `sudo pip uninstall pycoreconf`).

**Comment by alex-fddz** [comment]
I've updated the module and re-tested this case. Works as expected. Closing issue.
